f = read_function(')
clc();
figure(1);
subplot(2,2,1);
hold on;
plot(f(:,1),f(:,2),'b');
hold on;
plot(f(:,1),f(:,3),'r');
hold on;
legend('Current1','Current2');
xlabel('Time(ms)');
ylabel('Current(mA)');
grid on;
subplot(2,2,2);
plot(f(:,1),f(:,4));
xlabel('Time(ms)');
ylabel('Force(N)');
grid on;
subplot(2,2,3);
plot(f(:,1),f(:,5),'r');
hold on;
plot(f(:,1),f(:,6),'b');
xlabel('Time(ms)');
ylabel('Postion(rads)');
legend('Motor1','Motor2');
grid on;
subplot(2,2,4);
plot(f(:,7),f(:,8));
xlabel('X-Position');
xlabel('Y-Positon');
title('Coordination');
grid on;
